name: redux_persist
description: Persist Redux State with custom storage engines and serializers
version: 0.8.4
homepage: https://github.com/Cretezy/redux_persist/tree/master/packages/redux_persist

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  redux: ">=5.0.0 <6.0.0"
  synchronized: ^3.0.0

dev_dependencies:
  test: ^1.0.0
